categories:
  - title: "âœ¨ Features"
    labels:
      - "feature"
    commit_types:
      - feat

  - title: "ğŸ› Bugfixes"
    labels:
      - "bug"
    commit_types:
      - fix

  - title: "ğŸ“š Documentation"
    labels:
      - "documentation"
    commit_types:
      - docs

  - title: "ğŸ§¹ Maintenance"
    labels:
      - "chore"
    commit_types:
      - chore
