categories:
  features:
    title: "âœ¨ Features"
    labels:
      - "feature"
    commit_types:
      - feat

  bugfixes:
    title: "ğŸ› Bugfixes"
    labels:
      - "bug"
    commit_types:
      - fix

  documentation:
    title: "ğŸ“š Documentation"
    labels:
      - "documentation"
    commit_types:
      - docs

  maintenance:
    title: "ğŸ§¹ Maintenance"
    labels:
      - "chore"
    commit_types:
      - chore
